#%RAML 1.0
---

title: Customs Declarations
version: 2.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/xml

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Versioning
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
  - title: Errors
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
  - title: Testing
    content: !include docs/testing.md

/customs/declarations:
  /:
    post:
      displayName: Submit a Customs Declaration
      description: Allows submission of a Customs Declaration.
      headers:
        Accept:
          description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
          type: string
          required: true
          example: application/vnd.hmrc.2.0+xml
        Content-Type:
          description: Specifies the format of the request body, which must be XML. UTF-8 is the only valid character set.
           Download [schemas and example messages](/api-documentation/docs/api/download/customs-declarations/2.0/wco-declaration-schemas.zip).
          type: string
          required: true
          example: application/xml; charset=UTF-8
        X-Badge-Identifier:
            description: Represents the end-user who is interacting with the subscribed application. Required for CSP users. Must be numeric or upper case letters with a minimum length of 6 and a maximum length of 12.
            type: string
            required: false
            example: ABC123

      (annotations.scope): "write:customs-declaration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declaration" ] } ]
      body:
        application/xml:
          type: !include schemas/customs/wrapper_submit.xsd
          example: !include examples/example_submission_declaration_202.xml
      responses:
        202:
        400:
          body:
            application/xml:
              description: Invalid XML Payload
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                      <code>BAD_REQUEST</code>
                      <message>Payload is not valid according to schema</message>
                      <errors>
                          <error>
                              <code>xml_validation_error</code>
                              <message>Error at line 13, column 13: no declaration found for element 'unknown'</message>
                          </error>
                      </errors>
                  </errorResponse>
        500:
          body:
            application/xml:
              description: Internal server error
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                      <code>INTERNAL_SERVER_ERROR</code>
                      <message>Internal server error</message>
                  </errorResponse>

  /cancellation-requests:
      post:
        displayName: Submit a cancellation request
        description: Allows submission of a cancellation request.
        headers:
          Accept:
            description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
            type: string
            required: true
            example: application/vnd.hmrc.2.0+xml
          Content-Type:
            description: Specifies the format of the request body, which must be XML. UTF-8 is the only valid character set.
             Download [schemas and example messages](/api-documentation/docs/api/download/customs-declarations/2.0/wco-declaration-schemas.zip).
            type: string
            required: true
            example: application/xml; charset=UTF-8
          X-Badge-Identifier:
              description: Represents the end-user who is interacting with the subscribed application. Required for CSP users. Must be numeric or upper case letters with a minimum length of 6 and a maximum length of 12.
              type: string
              required: false
              example: ABC123

        (annotations.scope): "write:customs-declaration"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declaration" ] } ]
        body:
          application/xml:
            type: !include schemas/customs/wrapper_cancel.xsd
            example: !include examples/example_cancellation_declaration_202.xml
        responses:
          202:
          400:
            body:
              application/xml:
                description: Invalid XML Payload
                type: !include schemas/customs/error.xsd
                example: |
                    <?xml version="1.0" encoding="UTF-8"?>
                    <errorResponse>
                        <code>BAD_REQUEST</code>
                        <message>Payload is not valid according to schema</message>
                        <errors>
                            <error>
                                <code>xml_validation_error</code>
                                <message>Error at line 13, column 13: no declaration found for element 'unknown'</message>
                            </error>
                        </errors>
                    </errorResponse>
          500:
            body:
              application/xml:
                description: Internal server error
                type: !include schemas/customs/error.xsd
                example: |
                    <?xml version="1.0" encoding="UTF-8"?>
                    <errorResponse>
                        <code>INTERNAL_SERVER_ERROR</code>
                        <message>Internal server error</message>
                    </errorResponse>

  /file-upload:
      post:
        displayName: Submit an upload initiate request
        description: Obtain a signed URL to upload a file to
        headers:
          Accept:
            description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
            type: string
            required: true
            example: application/vnd.hmrc.1.0+xml
          Content-Type:
            description: Specifies the format of the request body, which must be XML. UTF-8 is the only valid character set.
             Download [schemas and example messages](/api-documentation/docs/api/download/customs-declarations/1.0/wco-declaration-schemas.zip).
            type: string
            required: true
            example: application/xml; charset=UTF-8
          X-Badge-Identifier:
              description: Represents the end-user who is interacting with the subscribed application. Required for CSP users. Must be numeric or upper case letters with a minimum length of 6 and a maximum length of 12.
              type: string
              required: false
              example: ABC123

        (annotations.scope): "write:customs-declaration"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declaration" ] } ]
        body:
          application/xml:
            type: !include schemas/wco/declaration/FileUpload.xsd
            example: !include examples/example_file_upload_202.xml
        responses:
          200:
            body:
              example: |
                 <?xml version="1.0" encoding="UTF-8"?>
                 <fileUpload>
                   <href>https://bucketName.s3.eu-west-2.amazonaws.com</href>
                   <X-Amz-Algorithm>AWS4-HMAC-SHA256</X-Amz-Algorithm>
                   <X-Amz-Expiration>2018-02-09T12:35:45.297Z</X-Amz-Expiration>
                   <X-Amz-Signature>xxxx</X-Amz-Signature>
                   <key>xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</key>
                   <acl>private</acl>
                   <X-Amz-Credential>ASIAxxxxxxxxx/20180202/eu-west-2/s3/aws4_request</X-Amz-Credential>
                   <policy>xxxxxxxx==</policy>
                 </fileUpload>
          400:
            body:
              application/xml:
                description: Invalid XML Payload
                type: !include schemas/customs/error.xsd
                example: |
                    <?xml version="1.0" encoding="UTF-8"?>
                    <errorResponse>
                        <code>BAD_REQUEST</code>
                        <message>Payload is not valid according to schema</message>
                        <errors>
                            <error>
                                <code>xml_validation_error</code>
                                <message>Error at line 13, column 13: no declaration found for element 'unknown'</message>
                            </error>
                        </errors>
                    </errorResponse>
          500:
            body:
              application/xml:
                description: Internal server error
                type: !include schemas/customs/error.xsd
                example: |
                    <?xml version="1.0" encoding="UTF-8"?>
                    <errorResponse>
                        <code>INTERNAL_SERVER_ERROR</code>
                        <message>Internal server error</message>
                    </errorResponse>

  /clearance:
    post:
      displayName: Submit a Customs Clearance Declaration
      description: Allows submission of a Customs Clearance Declaration.
      headers:
        Accept:
          description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
          type: string
          required: true
          example: application/vnd.hmrc.2.0+xml
        Content-Type:
          description: Specifies the format of the request body, which must be XML. UTF-8 is the only valid character set.
           Download [schemas and example messages](/api-documentation/docs/api/download/customs-declarations/2.0/wco-declaration-schemas.zip).
          type: string
          required: true
          example: application/xml; charset=UTF-8
        X-Badge-Identifier:
            description: Represents the end-user who is interacting with the subscribed application. Required for CSP users. Must be numeric or upper case letters with a minimum length of 6 and a maximum length of 12.
            type: string
            required: false
            example: ABC123

      (annotations.scope): "write:customs-declaration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declaration" ] } ]
      body:
        application/xml:
          type: !include schemas/customs/wrapper_submit.xsd
          example: !include examples/example_submission_declaration_202.xml
      responses:
        202:
        400:
          body:
            application/xml:
              description: Invalid XML Payload
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                      <code>BAD_REQUEST</code>
                      <message>Payload is not valid according to schema</message>
                      <errors>
                          <error>
                              <code>xml_validation_error</code>
                              <message>Error at line 13, column 13: no declaration found for element 'unknown'</message>
                          </error>
                      </errors>
                  </errorResponse>
        500:
          body:
            application/xml:
              description: Internal server error
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                      <code>INTERNAL_SERVER_ERROR</code>
                      <message>Internal server error</message>
                  </errorResponse>

  /amend:
    post:
      displayName: Submit a Customs Amend Declaration
      description: Allows submission of a Customs Amend Declaration.
      headers:
        Accept:
          description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
          type: string
          required: true
          example: application/vnd.hmrc.2.0+xml
        Content-Type:
          description: Specifies the format of the request body, which must be XML. UTF-8 is the only valid character set.
           Download [schemas and example messages](/api-documentation/docs/api/download/customs-declarations/2.0/wco-declaration-schemas.zip).
          type: string
          required: true
          example: application/xml; charset=UTF-8
        X-Badge-Identifier:
            description: Represents the end-user who is interacting with the subscribed application. Required for CSP users. Must be numeric or upper case letters with a minimum length of 6 and a maximum length of 12.
            type: string
            required: false
            example: ABC123

      (annotations.scope): "write:customs-declaration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declaration" ] } ]
      body:
        application/xml:
          type: !include schemas/customs/wrapper_submit.xsd
          example: !include examples/example_submission_declaration_202.xml
      responses:
        202:
        400:
          body:
            application/xml:
              description: Invalid XML Payload
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                      <code>BAD_REQUEST</code>
                      <message>Payload is not valid according to schema</message>
                      <errors>
                          <error>
                              <code>xml_validation_error</code>
                              <message>Error at line 13, column 13: no declaration found for element 'unknown'</message>
                          </error>
                      </errors>
                  </errorResponse>
        500:
          body:
            application/xml:
              description: Internal server error
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                      <code>INTERNAL_SERVER_ERROR</code>
                      <message>Internal server error</message>
                  </errorResponse>

  /arrival-notification:
    post:
      displayName: Submit an Arrival Notification Declaration
      description: Allows submission of a Customs Arrival Notification Declaration.
      headers:
        Accept:
          description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
          type: string
          required: true
          example: application/vnd.hmrc.2.0+xml
        Content-Type:
          description: Specifies the format of the request body, which must be XML. UTF-8 is the only valid character set.
           Download [schemas and example messages](/api-documentation/docs/api/download/customs-declarations/2.0/wco-declaration-schemas.zip).
          type: string
          required: true
          example: application/xml; charset=UTF-8
        X-Badge-Identifier:
            description: Represents the end-user who is interacting with the subscribed application. Required for CSP users. Must be numeric or upper case letters with a minimum length of 6 and a maximum length of 12.
            type: string
            required: false
            example: ABC123

      (annotations.scope): "write:customs-declaration"
      securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declaration" ] } ]
      body:
        application/xml:
          type: !include schemas/customs/wrapper_submit.xsd
          example: !include examples/example_submission_declaration_202.xml
      responses:
        202:
        400:
          body:
            application/xml:
              description: Invalid XML Payload
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                      <code>BAD_REQUEST</code>
                      <message>Payload is not valid according to schema</message>
                      <errors>
                          <error>
                              <code>xml_validation_error</code>
                              <message>Error at line 13, column 13: no declaration found for element 'unknown'</message>
                          </error>
                      </errors>
                  </errorResponse>
        500:
          body:
            application/xml:
              description: Internal server error
              type: !include schemas/customs/error.xsd
              example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <errorResponse>
                      <code>INTERNAL_SERVER_ERROR</code>
                      <message>Internal server error</message>
                  </errorResponse>

  /status-request:
    /mrn:
      /{mrn}:
        uriParameters:
          mrn:
            description: Movement Reference Number
            type: string
            example: "ABC123"
        get:
          displayName: Request the status of Declaration
          description: Allows requesting the status of a Declaration.
          headers:
            Accept:
              description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
              type: string
              required: true
              example: application/vnd.hmrc.2.0+xml
            Content-Type:
              description: Specifies the format of the request body, which must be XML. UTF-8 is the only valid character set.
               Download [schemas and example messages](/api-documentation/docs/api/download/customs-declarations/2.0/wco-declaration-schemas.zip).
              type: string
              required: true
              example: application/xml; charset=UTF-8
            X-Badge-Identifier:
                description: Represents the end-user who is interacting with the subscribed application. Must be numeric or upper case letters with a minimum length of 6 and a maximum length of 12.
                type: string
                required: true
                example: ABC123
          (annotations.scope): "write:customs-declaration"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:customs-declaration" ] } ]
          responses:
            200:
              body:
                application/xml:
                  description: Successful response payload
                  type: !include schemas/wco/status/StatusQueryResponse.xsd
                  example: !include schemas/wco/status/StatusQueryResponseExample.xml
            500:
              body:
                application/xml:
                  description: Internal server error
                  type: !include schemas/customs/error.xsd
                  example: |
                      <?xml version="1.0" encoding="UTF-8"?>
                      <errorResponse>
                          <code>INTERNAL_SERVER_ERROR</code>
                          <message>Internal server error</message>
                      </errorResponse>
